apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: my-namespace
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# Request nginx periodically to simulate normal traffic
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-loop-deployment
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-loop
  template:
    metadata:
      labels:
        app: curl-loop
    spec:
      containers:
      - name: curl
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do curl -s -x '' http://nginx-service.my-namespace.svc.cluster.local 2>&1 1> /dev/null; sleep 0.2; done"]
