kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-role
  labels:
    {{- include "charts.labels" . | nindent 4 }}
rules:
  # exporter needs to get pods to export metrics
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch" ]
  # exporter needs to get chaos experiments
  - apiGroups: [ "chaos-mesh.org" ]
    resources:
      - "*"
    verbs: [ "get", "list", "watch" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-rolebinding
  labels:
    {{- include "charts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "charts.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
